### ISSUE TITLE
bcgs2 iterative solver problems with intel 19.0, 19.1 compilers

### ISSUE THREAD

**Issue by amloftus** [adda-team/adda#286] opened 2021-02-02 23:17 UTC
I'm running ADDA v1.2 on a cluster and have been getting segmentation faults when trying to use the bcgs2 iterative solver when ADDA is compiled using intel 19 compilers. Using the qmr2 solver works fine, albeit slower. Using the 'DEBUGFULL' option (no optimization) in the Makefile seems to take care of the problem, although the problem persists when using the 'DEBUG' option (-O2 optimization). Has anyone else experienced this problem? Note that both solvers work fine when ADDA is compiled using gcc or hcpx compilers.
Thanks!

**Comment by myurkin** [comment] 2021-02-03 02:51
Can you please test the current ADDA version (the latest from the repository)?

Overall, this seems similar to #146 . Please also test other optimization options inside the Makefile (e.g. -01). If the issue is similar, then:
1) it is compiler bug
2) still, a workaround can probably be implemented in the code (adding some dumb statements, as was done for that issue). But I am not sure how I can get access to the modern icc compiler - so it is hard to do anything on my side.

**Comment by amloftus** [comment] 2021-02-03 17:34
The same problem with the 'bcgs2' solver is evident in the current version of ADDA (1.4.0) using optimization of -O1 and higher. Compiling with no optimization (DEBUGFULL) does work.

**Comment by amloftus** [comment] 2021-02-05 00:30
A bit more info if it'll help -- this is all using ADDA v1.4.0. I tried running sequential to see if this is an mpi issue, but also got a segmentation fault. I ran the TotalView debugging tool and apparently the segmentation fault is occurring within 'matvec.c' at line 354:

resultvec[j+Xcomp]=argvec[j+Xcomp]+cc_sqrt[mat][Xcomp]*Xmatrix[index+Xcomp*local_Nsmall];

called from the BCGS2 function at line 485 within 'iterative.c'. I'm a fortran person, haven't written in c in 20+ years, so this a bit out of my league. I also tried compiling with Intel 18.1 and got the same results (seg fault) for 'BCGS2' when optimization is O1, but works in full debug mode.

**Comment by myurkin** [comment] 2021-02-05 08:45
I will try to get hold of relatively recent version of Intel compiler and investigate this issue.

**Comment by myurkin** [comment] 2021-03-02 03:15
Adrian, can you please copy here the new details that you sent to adda-discuss.

Also, an immediate question is why do you prefer Intel compiler over, say, gcc. I have played a lot with both of them around 10 years ago trying to squeeze another 10-20% performance, but already then the gcc became more or less even with icc. Is the situation different now? So how much icc is faster (on other iterative solvers)?

The problem of using debugger in this case is that the issue is relevant only for the optimization, and then the debugging is much more difficult (the order of operations, memory allocation, etc. maybe very different from that given in the code). Still, debugging with -01 can give some insights. So let's focus on `OPTIONS=DEBUG` compilation mode.

Do you get any warnings during compilation? If no, can you please remove everything starting from `-diag-disable` from
https://github.com/adda-team/adda/blob/edf359dbd2894703d227c6b0c7998dea06cde7ef/src/Makefile#L408 
and recompile. This will produce a lot of spurious warnings, but some of them may potentially be related to segfault. If the number of warnings is large, please redirect the compilation messages to text file and attach it here (otherwise, just copy-paste them into the comment).

Another similar idea is to remove `-vec-report0` from
https://github.com/adda-team/adda/blob/edf359dbd2894703d227c6b0c7998dea06cde7ef/src/Makefile#L405
and recompile.

P.S. I must admit I got distracted by other things, but let's try to push this issue now.

**Comment by myurkin** [comment] 2021-03-04 15:05
I have managed to compile ADDA with latest Intel compilers (v. 2021.1) on Windows (it was hard since it uses Visual Studio environment - not suitable for existing makefiles). Actually this set includes two compilers: classic one `icl` (corresponds to `icc` on Linux), and new LLVM-based one (oneAPI) `icx`. 

I confirm the issue with `icl`: using `-O1` and higher produces errors in bcgs2 iterative solver (not segfault, but it pauses for a few second in the beginning of iterative and then breaks), using `-Od` (equivalent to `-O0` on Linux) works fine.

`icx` works fine with any optimizations (kind of expected, since it's internals are very different).

**Comment by amloftus** [comment] 2021-03-04 17:54
1 March 2021:
I will need to run O(10^6) ADDA simulations on our cluster in the near future and have found the bcgs2 solver to be extremely efficient in this regard. I am now working exclusively with v1.4.0. From before, using the TotalView debugging tool I've found the segmentation fault I'm seeing is related to line 354 in 'matvec.c'

resultvec[j+Xcomp]=argvec[j+Xcomp]+cc_sqrt[mat][Xcomp]*Xmatrix[index+Xcomp*local_Nsmall];

Evidently, 'index' in the above expression attains an extremely large negative value, although it's not clear why (corrupted memory elsewhere in the code?) or if this is the true cause of the fault. I noted that 'resultvec' is associated with a bad address when the fault occurs. To reiterate, this fault occurs only when optimization is used during compilation with newer Intel compilers, i.e., versions 17.x, 18.x, 19.x, and 20.x. I am wondering if there is anything else I might be able to test on my end to help resolve this issue or find a workaround as I know access to the newer Intel compilers may be an issue on your end. If so, please let me know.

4 March 2021:
I recompiled with your suggested changes to the Makefile and have attached a text file of the messages displayed.

[ADDAmpi_log_compile_icc_DEBUG.txt](https://github.com/adda-team/adda/files/6085659/ADDAmpi_log_compile_icc_DEBUG.txt)

**Comment by myurkin** [comment] 2021-03-05 17:46
I have tested the same Intel compilers on Linux cluster (updating the Makefile on the way - https://github.com/adda-team/adda/commit/6447ec0c1858790b572c8a7ce71a780ed3fef158). The conclusion is the same as on Windows (my previous comment), the issue is present for classic Intel compiler.

I will then try to find some workaround for this issue. But the comment inside the code for bcgs2 iterative solver says that the issue has been present since icc version 11.1, but I do not remember whether I have already tried to solve it (or just left it be).

**Comment by myurkin** [comment] 2021-03-07 17:53
Andrian, I have just committed a workaround in the code that should solve this issue. Now bcgs2 iterative solve works fine for me in all environments described above. I have also run tests from `tests/2exec/` on Windows, and executables produced using both Intel compilers produce correct results in all tests.

Can you please verify it for your compiler and environment?

**Comment by amloftus** [comment] 2021-03-09 16:36
Hi Maxim, I compiled the updated code with -O1 and -O3 optimization on Intel 19.1 and the bcgs2 iterative solver now works! I have been able to successfully run both a coated sphere and more complex aggregate on two different clusters.
I'll keep you informed if I encounter any further issues with this. Thanks!

**Closed** 2021-03-09 16:45 UTC
Labels: bug, comp-Logic, comp-Scripts, pri-Medium
