### ISSUE TITLE
No convergence above size parameter x=16

### ISSUE THREAD

**Issue by Dr-Piedra** [adda-team/adda#215] opened 2016-02-13 15:57 UTC
I am running ADDA_MPI in surface mode on a grid parallel system of 64 cores. For testing, I have set the simple case of the substrate having the index of ref =1.5 and the particle being a sphere of m=1.33+i0.05. The program works fine for particles of size parameter x<16, but I need to run particles around x~80. I have tried doubling the parameters: "dpl" up to 30 and decrease the "eps" up to 2. I may have the option to increase the number of cores. However, I am not sure if the lack of convergence is due to system memory. The first error that appears shows _**"nec2c: No convergence in gshank() - aborting"**_

I am attaching the output files with the error log. Help would be extremely appreciated. 
[error_log.zip](https://github.com/adda-team/adda/files/129229/error_log.zip)
Regards,
Patricio Piedra

**Comment by myurkin** [comment] 2016-02-13 17:11
Patricio,
- please provide the full command line of corresponding ADDA run.
- have you tested it in sequential mode (should not matter, but just in case)?
- overall, such behavior is not surprising and need to be solved along the systematic development mentioned in #176. It would be great if anybody is willing to look into it.

For now there are also two simple workaround to try:
- increase `MAXH` on line 69 of `somnec.c`. This can work if you can waste computer resources to reach high accuracy when you don't really need it (as described in #176).
- comment out line 543 (and probably 544) of `somnec.c`. I am not sure but that will probably just return the result after `MAXH` results even if it is not deemed converged. And that would be exactly the behavior you need for large-distance cases. However, this will add one extra uncertainly in your final results. But you are going to test them against some independent reference anyway, aren't you?

**Comment by faraonlatino** [comment] 2016-02-13 19:21
The ADDA_MPI command (in SunGrid) in parallel mode that I am using is: 
_**mpirun -np $NSLOTS $ADDA_MPI -dir $JOB_NAME -m 1.33 .05 -size 34 -surf 17 1.5 0 -eps 2 -dpl 30**

I tried running this command in sequential mode, and obtained good results.
ADDA -dir test_16 -size 32 -surf 16 1.5 0 -m 1.33 .05

But when I increased the radius to 17 run in sequential mode: 
ADDA -dir test_17 -size 34 -surf 17 1.5 0 -m 1.33 .05
I get the same error: 
_**z=10.3084, rho=4.50683
nec2c: No convergence in gshank() - aborting**_

I will try to recompile my ADDA_MPI as you described above, and I will let you know my results, any other advice will greatly be appreciated.
Thanks for the response.

**Comment by myurkin** [comment] 2016-02-13 21:09
I can confirm the error with this command line (sequential mode on my laptop), so i do not have any new suggestions at the moment.

**Comment by myurkin** [comment] 2020-12-04 03:45
I've taken one more look at that. The second solution above (comment out line 543) seems to have no sense, since in this case no result of integration is produced at all (`sum` array is not updated). However, increasing MAXH clearly works. I increased it to `MAXH=500` in d2a495c and could simulate fine up to size x=80 (haven't tried larger ones).
```
... adda_mpi -size 160 -surf 80 1.5 0 -m 1.33 .05
```
The drawback is the computational time, now the Sommerfeld integrals take the time equivalent up to about 1300 iterations (for smaller sizes it is about 200 iterations). The good thing, this change doesn't significantly increase the computational time for smaller sizes, e.g. for `adda -size 32 -surf 16 1.5 0 -m 1.33 .05`. In other words, the use of MAXH is adaptive.

So this change should make all simulations reachable on the desktop (including those addressed by precompiled Windows binaries). If larger sizes are required on a cluster, further increase of MAXH is straightforward.

Surely, this is only a reasonable temporary fix, ultimate solution should be obtained within #176.

@Dr-Piedra , can you please confirm this?

**Closed by myurkin** 2020-12-04 03:45 UTC
Labels: bug, comp-Logic, pri-High, surf
