### ISSUE TITLE
Issue in OpenCL implementation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [adda-team/adda#207] opened 2015-08-12 07:55 UTC
```
Hi, 

there seems to be an issue in the current OpenCL implementation from the SVN:

I use svn r1406 with OCL_BLAS enabled on an AMD GPU. For example with
adda_ocl -orient 49 43 25 -shape ellipsoid 1.4 2.2 -eq_rad 10 -iter bicg
the calculation for the second incident polarization fails. The relative norm 
of the residual becomes extremely large and no convergence is achieved. When I 
add "-init_field inc" to the command line, I get convergence.

However, the results from the OpenCL version in the SVN substantially deviate 
from the results obtained using other versions of ADDA. I have attached a table 
with some numbers for C_ext in various cases. Results for r1406/seq, 1.3b4/ocl, 
1.3b4/seq always agree, but r1406/ocl always deviates from this. The last block 
(where the qmr solver is used) suggests that the issue probably is in the 
current opencl implementation, not directly in the new OpenCL-bicg 
implementation.

This issue does not depend much on the geometry (I tested some other 
geometries).

Please let me know if you need more information on this.

```

Original issue reported on code.google.com by `jgasteiger80` on 8 May 2015 at 8:59

Attachments:
- [cext_cases.txt](https://storage.googleapis.com/google-code-attachments/a-dda/issue-207/comment-0/cext_cases.txt)

**Comment by mapclyps** [comment] 2015-09-22 12:43
I finally managed to reproduce this issue on a Nvidia GTX 970 using recent versions of the clFFT (v2.6.1) and clBLAS (v2.6.0) libraries. However, the issue occurs for me only when OCL_BLAS is set using the bicg solver. For the qmr solver I get convergence for this case and the results agree with the seq version. So probably it was connected to a particular version of the clFFT library which is fixed now. The issue with the current version of the clBLAS library (which is used when OCL_BLAS is set) and the bicg solver remains. I will try it also on an AMD 7970 GHz ed. and see if it is the same there.

**Comment by myurkin** [comment] 2015-09-22 18:39
Great, we have the first progress-comment on github! (although there is still a lot to do with the move itself)

I guess the issue is then related to #204 . By the way, Marcus, how easy it is to use new versions of clFFT with ADDA? What are the required code changes? I.e. what is the easiest way for Joseph to test your conclusion? If we can limit the issue to OCL_BLAS that would be already something

**Comment by mapclyps** [comment] 2015-09-23 09:19
I just send #211 which should address this naming issue. From there it should be easy to try if the issue is a general OpenCL issue. At least with the recent clFFT and clBLAS libraries I can see only the non-convergence for the bicg solver when OCL_BLAS is enabled but not the wrong results for qmr or bicg with OCL_BLAS disabled. I also tried it now on a AMD 7970 with the same result.

**Comment by jgasteiger** [comment] 2015-09-23 13:41
I now have ADDA running with the recent clFFT and clBLAS libraries on the AMD W8100. Thank you for the update.

While trying around, I noticed the following things on my machine:

1) I get the same behaviour with the recent clFFT and clBLAS libraries as I get for the older clAMDxxx libraries.

2) The behaviour depends on whether I uncomment in the ocl/Makefile

LDFLAGS +=-Wl,--unresolved-symbols=ignore-in-shared-libs
or 
LDLIBS += -lpthread

The behaviour reported last May was for adda_ocl with "LDLIBS += -lpthread" enabled. Using 'LDFLAGS +=-Wl,--unresolved-symbols=ignore-in-shared-libs' instead, I see the behaviour Markus sees: If OCL_BLAS is disabled, results for seq and ocl agree well; if OCL_BLAS is enabled, there are some cases of non-convergence for the bicg solver.

**Comment by mapclyps** [comment] 2015-09-23 15:00
Hey Joseph, this is a great catch! 
Considering your findings, without the `LDFLAGS +=-Wl,--unresolved-symbols=ignore-in-shared-libs`, I can reproduce all results now which you reported in May. At least on my AMD card. Unfortunately adda does not compile for me on the Nvidia system when these LDFLAGS are not set.
I find it very strange that it compiles with- and without the flag on the AMD systems, but gives different results. I'm not so familiar with these flags, but maybe @myurkin has in idea where this effect comes from.

`LDLIBS += -lpthread` was not needed for me and did not change anything in the results.

The OCL_BLAS option with the no-convergence-issue with the bicg solver seems like another independent issue.

**Comment by mapclyps** [comment] 2015-09-24 13:44
@jgasteiger can you try the current revision with the `LDFLAGS +=-Wl,--unresolved-symbols=ignore-in-shared-libs` set? There should be convergence and correct results now for the second polarization with the bicg solver when `OCL_BLAS` is set. It was some memory synchronization issue (see #212 for technical details). Depending on your CPU speed it can make a big difference if `OCL_BLAS` is set. In my case it is more than a factor of 2 difference in performance and for your particular example on my Radeon based system.

We should keep this issue open for the wrong results without the `LDFLAGS +=-Wl,--unresolved-symbols=ignore-in-shared-libs` set. I'm still wondering where this comes from....

**Comment by jgasteiger** [comment] 2015-09-25 08:36
The current version with LDFLAGS +=-Wl,--unresolved-symbols=ignore-in-shared-libs set works fine here also for the second polarization. Thank you for the fix.

Some numbers for the above example here on the W8100: adda_ocl takes 65sec in version 1.3b4, 12.0sec in current git version without BLAS, and 9.7sec with BLAS enabled.

**Comment by myurkin** [comment] 2015-09-25 08:41
Concerning the `LDFLAGS +=-Wl,--unresolved-symbols=ignore-in-shared-libs` I can't remember more than given in the corresponding comment in `ocl/Makefile`:
This is caused by Nvidia OpenCL libraries on Linux (hopefully it will disappear in next releases of this library)
> The drawback of this workaround is that a warning would appear at each execution of adda_ocl. If you don't like it, provide another libOpenCL.so (e.g. that from AMD, or better - open-source one from https://forge.imag.fr/projects/ocl-icd/) for linking.

It is really strange that this igrore-warning setting affects the calculated results. I could understand if we are linking to different functions in OpenCL.so, but this flag should not affect the linking itself. So we need to investigate this further. 

By the time of 1.3 release we need either to understand and fix it or at least to uncomment `LDFLAGS +=-Wl,--unresolved-symbols=ignore-in-shared-libs` by default as a workaround (and update the comment near it). I do not know, if this may have any unexpected drawbacks in the future.

**Comment by myurkin** [comment] 2020-11-30 19:02
Concerning the `LDFLAGS +=-Wl,--unresolved-symbols=ignore-in-shared-libs`, it still helps in some rare cases, but it doesn't seem to be persistent. Thus, we just keep it in Makefile comments and mention it in [OpenCL](../wiki/OpenCL). This issue can then be considered resolved.

**Closed by myurkin** 2020-11-30 19:02 UTC
Labels: OpenCL, accuracy, bug, pri-Medium
